project:
  type: book
  output-dir: docs
  resources:
    - .nojekyll

book:
  title: "Student Dissertations and Research Projects"
  author: "Brian Paul Boyle"
  date: "2026-08-13"
  page-footer:
    left: "© 2026 Brian Paul Boyle"
    right:
      - text: "CC BY-NC-ND 4.0"
        href: https://creativecommons.org/licenses/by-nc-nd/4.0/
  chapters:
    - index.qmd
    - practical_tips.qmd
    - part: Chapters
      chapters:
        - research_questions.qmd
        - lit_reviews.qmd
        - structure.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

